---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: allezon
  name: forwarder
  labels:
    app: forwarder
spec:
  replicas: 3
  selector:
    matchLabels:
      app: forwarder
  template:
    metadata:
      labels:
        app: forwarder
    spec:
      containers:
      - name: forwarder
        image: docker.io/rzetelskik/allezon-forwarder:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: 64Mi
            cpu: 100m