---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: allezon
  name: collector
  labels:
    app: collector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: docker.io/rzetelskik/allezon-collector:latest
        imagePullPolicy: Always
