---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: allezon-analytics
  name: allezon-analytics
  labels:
    app: allezon-analytics
spec:
  replicas: 3
  selector:
    matchLabels:
      app: allezon-analytics
  template:
    metadata:
      labels:
        app: allezon-analytics
    spec:
      containers:
      - name: allezon-analytics
        image: docker.io/rzetelskik/allezon-analytics
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
          failureThreshold: 3
