---
apiVersion: v1
kind: Service
metadata:
  namespace: allezon-analytics
  name: allezon-analytics
  labels:
    app: allezon-analytics
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: allezon-analytics