---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: allezon
  name: service
  labels:
    app: service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service
  template:
    metadata:
      labels:
        app: service
    spec:
      containers:
      - name: service
        image: docker.io/rzetelskik/allezon-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
          failureThreshold: 3
        resources:
          requests:
            memory: 64Mi
            cpu: 100m
