---
apiVersion: v1
kind: Service
metadata:
  namespace: allezon
  name: service
  labels:
    app: service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: service
