apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  namespace: kafka
  name: kafka-cluster
spec:
  kafka:
    version: 3.2.0
    replicas: 3
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: tls
#    authorization:
#      type: simple
    config:
      auto.create.topics.enable: "false"
      delete.topic.enable: "true"
      num.partitions: 3
      default.replication.factor: 2
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      inter.broker.protocol.version: "3.2"
      log.segment.bytes: 21474836
      log.segment.delete.delay.ms: 1000
      log.retention.ms: 3600000
      log.retention.bytes: 214748364
      log.retention.check.interval.ms: 20000
      log.cleanup.policy: "delete"
      log.cleaner.enable: "true"
    storage:
      class: local-xfs
      deleteClaim: false
      type: persistent-claim
      size: 8Gi
    template:
      pod:
        topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: kafka
  zookeeper:
    replicas: 3
    storage:
      class: local-xfs
      deleteClaim: false
      type: persistent-claim
      size: 2Gi
    template:
      pod:
        topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: zookeeper
  entityOperator:
    topicOperator: { }
    userOperator: { }
