apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  namespace: kafka
  name: kafka-cluster
spec:
  kafka:
    version: 3.2.0
    replicas: 1
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: tls
    - name: external
      port: 9094
      type: nodeport
      tls: false
    # authorization:
    #   type: simple
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.2"
    storage:
      class: local-volumes
      deleteClaim: true
      type: persistent-claim
      size: 16Gi
  zookeeper:
    replicas: 1
    storage:
      class: local-volumes
      deleteClaim: true
      type: persistent-claim
      size: 16Gi
  entityOperator:
    topicOperator: { }
    userOperator: { }
