apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  namespace: kafka
  name: kafka-cluster
spec:
  kafka:
    version: 3.2.0
    replicas: 5
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: tls
#    authorization:
#      type: simple
    config:
      auto.create.topics.enable: "false"
      delete.topic.enable: "true"
      num.partitions: 5
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
      log.segment.bytes: 107374182
      log.segment.delete.delay.ms: 1000
      log.retention.ms: 3600000
      log.retention.bytes: 1073741824
      log.retention.check.interval.ms: 20000
      log.cleanup.policy: "delete"
      log.cleaner.enable: "true"
    storage:
      class: local-xfs
      deleteClaim: false
      type: persistent-claim
      size: 4Gi
  zookeeper:
    replicas: 5
    storage:
      class: local-xfs
      deleteClaim: false
      type: persistent-claim
      size: 4Gi
  entityOperator:
    topicOperator: { }
    userOperator: { }
