apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  namespace: kafka
  name: kafka-cluster
spec:
  kafka:
    version: 3.2.0
    replicas: 5
    listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: tls
#    authorization:
#      type: simple
    config:
      auto.create.topics.enable: "false"
      delete.topic.enable: "true"
      default.replication.factor: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
      log.segment.bytes: 1073741824
      log.retention.bytes: 7516192768
      log.retention.check.interval.ms: 300000
      log.cleanup.policy: compact
    storage:
      class: local-volumes
      deleteClaim: false
      type: persistent-claim
      size: 16Gi
  zookeeper:
    replicas: 5
    storage:
      class: local-volumes
      deleteClaim: false
      type: persistent-claim
      size: 16Gi
  entityOperator:
    topicOperator: { }
    userOperator: { }
