---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: collector-table
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  config:
    retention.ms: 86400000
    retention.bytes: 4294967296
