---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-user
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
    - resource:
        type: topic
        name: kafka-topic
        patternType: literal
      operation: Read
      host: "*"
    - resource:
        type: topic
        name: kafka-topic
        patternType: literal
      operation: Describe
      host: "*"
    - resource:
        type: group
        name: kafka-group
        patternType: literal
      operation: Read
      host: "*"
    - resource:
        type: topic
        name: kafka-topic
        patternType: literal
      operation: Write
      host: "*"
    - resource:
        type: topic
        name: kafka-topic
        patternType: literal
      operation: Create
      host: "*"
    - resource:
        type: topic
        name: kafka-topic
        patternType: literal
      operation: Describe
      host: "*"