---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: user-profile
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  config:
    retention.ms: 3600000
    retention.bytes: 1073741824